[package]
name = "ltrace-decoder"
version = "0.1.0"
edition = "2021"
authors = ["iansseijelly"]


[dependencies]
object = "0.36"
capstone = "0.12"
clap = { version = "4.5.18", features = ["derive"] }


